/**
 * Job Notification Tracker — Realistic Indian Tech Jobs Dataset (60)
 */

const JOBS_DATA = [
  {
    id: 1,
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹40k–₹80k/month Internship",
    applyUrl: "https://amazon.in/careers/intern",
    description: "Work on real-world projects alongside senior engineers. Build scalable systems and learn AWS technologies. Mentorship provided throughout the internship."
  },
  {
    id: 2,
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "SDLC", "Testing"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.tcs.com/get",
    description: "12-month comprehensive training program. Work on client projects in banking or retail domains. Full-time conversion opportunity post-training."
  },
  {
    id: 3,
    title: "Junior Backend Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "PostgreSQL", "Redis", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://razorpay.com/jobs",
    description: "Build and maintain payment APIs used by millions. Work with the core platform team. Fast-paced fintech environment with learning budget."
  },
  {
    id: 4,
    title: "Frontend Intern",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "https://freshworks.com/careers",
    description: "Develop UI components for Freshworks products. Collaborate with design and backend teams. Pre-placement offer for top performers."
  },
  {
    id: 5,
    title: "QA Intern",
    company: "Infosys",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Selenium", "Manual Testing", "JIRA", "SQL"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹25k/month Internship",
    applyUrl: "https://infosys.com/careers",
    description: "Assist in test case design and execution for enterprise applications. Learn automation frameworks. Structured internship with certification."
  },
  {
    id: 6,
    title: "Data Analyst Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel", "Tableau"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹20k–₹40k/month Internship",
    applyUrl: "https://swiggy.com/careers",
    description: "Analyze delivery and user behavior data. Create dashboards for business teams. Work with large-scale datasets in a product company."
  },
  {
    id: 7,
    title: "Java Developer (0-1)",
    company: "Wipro",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "MySQL", "Microservices"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "4–6 LPA",
    applyUrl: "https://wipro.com/careers",
    description: "Develop and maintain Java applications for Fortune 500 clients. Work on banking or healthcare domains. Comprehensive onboarding program."
  },
  {
    id: 8,
    title: "Python Developer (Fresher)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "REST APIs"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "4–7 LPA",
    applyUrl: "https://zoho.com/careers",
    description: "Build features for Zoho's suite of products. Work in small teams with direct ownership. In-house training and mentorship culture."
  },
  {
    id: 9,
    title: "React Developer (1-3)",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "Node.js"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://flipkartcareers.com",
    description: "Build customer-facing e-commerce experiences at scale. Work on performance optimization and new features. Strong engineering culture."
  },
  {
    id: 10,
    title: "SDE Intern",
    company: "Microsoft",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C#", "Azure", "Algorithms", "Problem Solving"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹50k–₹90k/month Internship",
    applyUrl: "https://careers.microsoft.com",
    description: "Contribute to Microsoft products. Access to Azure credits and learning resources. High conversion rate to full-time offers."
  },
  {
    id: 11,
    title: "Graduate Engineer Trainee",
    company: "Accenture",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Cloud", "Agile", "DevOps"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3.5–5 LPA",
    applyUrl: "https://accenture.com/in-en/careers",
    description: "Training in full-stack development and cloud technologies. Deployed to projects after 3 months. Global exposure opportunities."
  },
  {
    id: 12,
    title: "Backend Developer",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Go", "Kafka", "Cassandra", "Distributed Systems"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "12–20 LPA",
    applyUrl: "https://phonepe.com/careers",
    description: "Build payment and wallet systems handling millions of transactions daily. Work with high-throughput distributed systems. Ownership culture."
  },
  {
    id: 13,
    title: "Frontend Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "Next.js", "TypeScript", "CSS"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://cred.club/careers",
    description: "Build UI for a fintech product used by premium users. Focus on performance and polish. Strong design collaboration."
  },
  {
    id: 14,
    title: "DevOps Intern",
    company: "Cognizant",
    location: "Pune",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Docker", "Kubernetes", "AWS", "CI/CD"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹18k–₹35k/month Internship",
    applyUrl: "https://cognizant.com/careers",
    description: "Support cloud infrastructure for enterprise clients. Learn DevOps practices and tooling. Structured learning path provided."
  },
  {
    id: 15,
    title: "Full Stack Developer (0-1)",
    company: "Juspay",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["React", "Node.js", "PostgreSQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "8–12 LPA",
    applyUrl: "https://juspay.in/careers",
    description: "Build payment SDKs and merchant dashboards. Work in a product-focused fintech. Strong mentorship and code review culture."
  },
  {
    id: 16,
    title: "Data Engineer Intern",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Spark", "SQL", "Airflow"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://paytm.com/careers",
    description: "Build data pipelines for analytics and ML teams. Work with large-scale financial data. Exposure to data architecture."
  },
  {
    id: 17,
    title: "Software Engineer",
    company: "IBM",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Cloud", "AI/ML", "Kubernetes"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "8–15 LPA",
    applyUrl: "https://ibm.com/careers",
    description: "Work on IBM Cloud or Watson projects. Opportunity to contribute to open source. Global team collaboration."
  },
  {
    id: 18,
    title: "SDE Intern",
    company: "Google",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C++", "Algorithms", "System Design", "Python"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹80k–₹1.2L/month Internship",
    applyUrl: "https://careers.google.com",
    description: "Work on impactful projects across Search, Ads, or Cloud. Mentorship from senior engineers. High bar, high growth environment."
  },
  {
    id: 19,
    title: "Associate Software Engineer",
    company: "Capgemini",
    location: "Mumbai",
    mode: "Onsite",
    experience: "0-1",
    skills: [".NET", "C#", "SQL Server", "Azure"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "3.5–5.5 LPA",
    applyUrl: "https://capgemini.com/careers",
    description: "Develop enterprise applications for global clients. Training in Microsoft stack. Career progression framework available."
  },
  {
    id: 20,
    title: "Mobile Developer (1-3)",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React Native", "iOS", "Android", "TypeScript"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://swiggy.com/careers",
    description: "Build consumer apps used by millions daily. Work on performance and new features. Remote-first team with async culture."
  },
  {
    id: 21,
    title: "Backend Intern",
    company: "ShareChat",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "MongoDB", "Redis"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹35k–₹55k/month Internship",
    applyUrl: "https://sharechat.com/careers",
    description: "Build scalable APIs for a social media platform. Work with high-traffic systems. Startup environment with ownership."
  },
  {
    id: 22,
    title: "Java Developer",
    company: "Oracle",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Oracle DB", "Spring", "Microservices"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "8–14 LPA",
    applyUrl: "https://oracle.com/careers",
    description: "Contribute to Oracle Cloud or Database products. Work with enterprise-grade systems. Learning and certification support."
  },
  {
    id: 23,
    title: "Product Engineer (0-1)",
    company: "Postman",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["JavaScript", "Node.js", "React", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–16 LPA",
    applyUrl: "https://postman.com/careers",
    description: "Build features for the Postman API platform. Fully remote role. Strong product and engineering collaboration."
  },
  {
    id: 24,
    title: "QA Engineer",
    company: "Dell",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Automation", "Selenium", "Java", "TestNG"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "5–8 LPA",
    applyUrl: "https://dell.com/careers",
    description: "Ensure quality of Dell software products. Develop automated test suites. Structured career path in QA."
  },
  {
    id: 25,
    title: "SDE Intern",
    company: "Intuit",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "React", "AWS", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹45k–₹75k/month Internship",
    applyUrl: "https://intuit.com/careers",
    description: "Work on TurboTax or QuickBooks products. Solve problems for millions of users. Inclusive and supportive culture."
  },
  {
    id: 26,
    title: "Frontend Developer",
    company: "SAP",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["SAP UI5", "JavaScript", "Fiori", "React"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "8–14 LPA",
    applyUrl: "https://sap.com/careers",
    description: "Build enterprise UI for SAP products. Work with SAP Cloud platform. Certification and training provided."
  },
  {
    id: 27,
    title: "Graduate Engineer Trainee",
    company: "L&T Infotech",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Web Technologies", "Testing"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://lntinfotech.com/careers",
    description: "Training program in software development. Project assignment after initial training. Conversion to permanent role."
  },
  {
    id: 28,
    title: "Backend Developer (1-3)",
    company: "Udaan",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Java", "Kafka", "Elasticsearch", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "12–22 LPA",
    applyUrl: "https://udaan.com/careers",
    description: "Build B2B e-commerce platform. High-scale distributed systems. Fast-growing startup with strong engineering."
  },
  {
    id: 29,
    title: "Data Science Intern",
    company: "Dunzo",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "ML", "SQL", "Statistics"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://dunzo.com/careers",
    description: "Work on recommendation or logistics optimization models. Real-world ML problems. Mentorship from data science team."
  },
  {
    id: 30,
    title: "React Developer",
    company: "CleverTap",
    location: "Mumbai",
    mode: "Remote",
    experience: "0-1",
    skills: ["React", "Redux", "JavaScript", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://clevertap.com/careers",
    description: "Build analytics and engagement dashboards. SaaS product used globally. Remote-first with flexible hours."
  },
  {
    id: 31,
    title: "SDE Intern",
    company: "Adobe",
    location: "Noida",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C++", "JavaScript", "Algorithms", "Data Structures"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹55k–₹90k/month Internship",
    applyUrl: "https://adobe.com/careers",
    description: "Contribute to Creative Cloud or Experience Cloud. Work on impactful products. Strong internship program with PPO."
  },
  {
    id: 32,
    title: "Full Stack Intern",
    company: "Unacademy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "Node.js", "MongoDB", "AWS"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹25k–₹45k/month Internship",
    applyUrl: "https://unacademy.com/careers",
    description: "Build features for the learning platform. Work on scalability challenges. Edtech with strong engineering culture."
  },
  {
    id: 33,
    title: "Java Developer (0-1)",
    company: "HCL Tech",
    location: "Noida",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring", "Oracle", "REST"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "3.5–5.5 LPA",
    applyUrl: "https://hcltech.com/careers",
    description: "Develop applications for global clients. Training in enterprise Java stack. Diverse project opportunities."
  },
  {
    id: 34,
    title: "DevOps Engineer",
    company: "Gojek",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Kubernetes", "Terraform", "AWS", "Python"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://gojek.com/careers",
    description: "Manage infrastructure for super app. Work with multiple product teams. High scale, fast-paced environment."
  },
  {
    id: 35,
    title: "Python Intern",
    company: "HackerRank",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "APIs"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "₹35k–₹55k/month Internship",
    applyUrl: "https://hackerrank.com/careers",
    description: "Build features for the technical assessment platform. Work on coding challenges and evaluations. Remote-first team."
  },
  {
    id: 36,
    title: "Frontend Developer (1-3)",
    company: "BrowserStack",
    location: "Mumbai",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "Vue", "Testing"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "12–20 LPA",
    applyUrl: "https://browserstack.com/careers",
    description: "Build developer tools UI. Work on testing platform used by thousands of companies. Fully remote, async culture."
  },
  {
    id: 37,
    title: "Backend Intern",
    company: "Instamojo",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "Redis"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://instamojo.com/careers",
    description: "Build payment and e-commerce APIs. Small team with high ownership. Learn full product development cycle."
  },
  {
    id: 38,
    title: "Software Engineer",
    company: "VMware",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Python", "Kubernetes", "Cloud"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "10–16 LPA",
    applyUrl: "https://vmware.com/careers",
    description: "Work on VMware Cloud or Tanzu products. Enterprise software at scale. Strong benefits and work-life balance."
  },
  {
    id: 39,
    title: "Graduate Engineer Trainee",
    company: "Tech Mahindra",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Selenium", "Agile", "SQL"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://techmahindra.com/careers",
    description: "Training in testing and development. Deployed to telecom or healthcare projects. Career growth framework."
  },
  {
    id: 40,
    title: "SDE Intern",
    company: "Directi",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Algorithms", "System Design", "Java", "Python"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹50k–₹80k/month Internship",
    applyUrl: "https://directi.com/careers",
    description: "Work on products across domains. High bar technical interviews. Strong engineering culture and mentorship."
  },
  {
    id: 41,
    title: "iOS Developer (0-1)",
    company: "Dream11",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Swift", "iOS SDK", "Xcode", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "8–14 LPA",
    applyUrl: "https://dream11.com/careers",
    description: "Build the fantasy sports app used by millions. Work on performance and new features. Fast-growing product company."
  },
  {
    id: 42,
    title: "Data Analyst",
    company: "Ola",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["SQL", "Python", "Excel", "Tableau"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "5–9 LPA",
    applyUrl: "https://olacabs.com/careers",
    description: "Analyze mobility and delivery data. Create reports for product and operations. Exposure to large-scale data."
  },
  {
    id: 43,
    title: "Full Stack Developer",
    company: "Policybazaar",
    location: "Gurgaon",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React", "Node.js", "MongoDB", "AWS"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "8–14 LPA",
    applyUrl: "https://policybazaar.com/careers",
    description: "Build insurance comparison and purchase flows. Fintech with strong product focus. Structured growth path."
  },
  {
    id: 44,
    title: "QA Intern",
    company: "MakeMyTrip",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Manual Testing", "API Testing", "Postman", "JIRA"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹18k–₹30k/month Internship",
    applyUrl: "https://makemytrip.com/careers",
    description: "Test travel booking platforms. Work with QA and dev teams. Learn testing best practices in product company."
  },
  {
    id: 45,
    title: "Backend Developer",
    company: "Groww",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["Java", "Spring", "Kafka", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "12–22 LPA",
    applyUrl: "https://groww.in/careers",
    description: "Build investment and trading platforms. Work with financial data at scale. Remote-first fintech with strong growth."
  },
  {
    id: 46,
    title: "Frontend Intern",
    company: "Meesho",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "Redux", "Responsive Design"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://meesho.com/careers",
    description: "Build seller and customer-facing features. Work on India's largest social commerce platform. PPO for top performers."
  },
  {
    id: 47,
    title: "DevOps Intern",
    company: "Hasura",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Docker", "Kubernetes", "AWS", "Terraform"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹40k–₹60k/month Internship",
    applyUrl: "https://hasura.io/careers",
    description: "Manage infrastructure for GraphQL platform. Open source company with global users. Fully remote with async work."
  },
  {
    id: 48,
    title: "React Developer (0-1)",
    company: "Groww",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "TypeScript", "Redux", "REST"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://groww.in/careers",
    description: "Build investment dashboard and trading UI. Work with product and design. Fast-paced fintech environment."
  },
  {
    id: 49,
    title: "Graduate Engineer Trainee",
    company: "Mindtree",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "Cloud", "Agile"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3.5–5 LPA",
    applyUrl: "https://mindtree.com/careers",
    description: "Training in digital technologies. Project allocation in 2-3 months. Global client exposure."
  },
  {
    id: 50,
    title: "Backend Intern",
    company: "Slack (Salesforce)",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Kafka", "AWS", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹60k–₹1L/month Internship",
    applyUrl: "https://salesforce.com/careers",
    description: "Work on Slack infrastructure. Contribute to real-time messaging systems. Strong mentorship and PPO rate."
  },
  {
    id: 51,
    title: "SDE Intern",
    company: "LinkedIn",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Distributed Systems", "Algorithms", "Data Structures"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹70k–₹1.1L/month Internship",
    applyUrl: "https://linkedin.com/careers",
    description: "Build features for the professional network. Work on large-scale systems. Excellent internship experience and conversion."
  },
  {
    id: 52,
    title: "Android Developer",
    company: "Spotify",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["Kotlin", "Android SDK", "Jetpack", "REST"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "15–25 LPA",
    applyUrl: "https://spotify.com/careers",
    description: "Build the Spotify Android app for millions of users. Work on streaming and personalization. Remote-first culture."
  },
  {
    id: 53,
    title: "Full Stack Intern",
    company: "BharatPe",
    location: "Delhi NCR",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "Node.js", "MongoDB", "AWS"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "₹25k–₹45k/month Internship",
    applyUrl: "https://bharatpe.com/careers",
    description: "Build merchant and payment features. Fintech with rapid growth. Learn from experienced engineers."
  },
  {
    id: 54,
    title: "Data Engineer",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Spark", "Airflow", "Snowflake"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "12–20 LPA",
    applyUrl: "https://flipkartcareers.com",
    description: "Build data pipelines for e-commerce analytics. Work with petabyte-scale data. Strong data engineering culture."
  },
  {
    id: 55,
    title: "Java Developer",
    company: "Atlassian",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["Java", "Spring", "AWS", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "18–28 LPA",
    applyUrl: "https://atlassian.com/careers",
    description: "Work on Jira, Confluence, or Trello. Fully remote. Strong engineering culture and work-life balance."
  },
  {
    id: 56,
    title: "Frontend Developer",
    company: "Innovaccer",
    location: "Noida",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "JavaScript", "Redux", "HTML/CSS"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "5–9 LPA",
    applyUrl: "https://innovaccer.com/careers",
    description: "Build healthcare analytics dashboards. Work on products used by hospitals. Mission-driven health tech."
  },
  {
    id: 57,
    title: "Backend Intern",
    company: "DealShare",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "Redis"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "₹22k–₹38k/month Internship",
    applyUrl: "https://dealshare.in/careers",
    description: "Build e-commerce backend systems. Work on inventory and order management. Fast-paced startup environment."
  },
  {
    id: 58,
    title: "SDE Intern",
    company: "Netflix",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Distributed Systems", "Data Structures"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹1L–₹1.5L/month Internship",
    applyUrl: "https://jobs.netflix.com",
    description: "Work on streaming platform infrastructure. High-impact projects. Selective program with excellent mentorship."
  },
  {
    id: 59,
    title: "ML Engineer (0-1)",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Python", "TensorFlow", "SQL", "MLOps"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–16 LPA",
    applyUrl: "https://razorpay.com/jobs",
    description: "Build fraud detection and risk models. Work with production ML systems. Strong ML engineering culture."
  },
  {
    id: 60,
    title: "Full Stack Developer",
    company: "Zepto",
    location: "Mumbai",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React", "Node.js", "PostgreSQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "12–22 LPA",
    applyUrl: "https://zeptonow.com/careers",
    description: "Build quick commerce platform. Work on speed and reliability. High-growth startup with strong engineering."
  }
];
